pipeline {
  agent any
  tools { maven 'Maven' }
  environment {
    SONAR_HOST_URL = 'http://sonarqube:9000'
    SONAR_TOKEN = credentials('sonar-token')
  }
  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/rmatos-pg/proj.git', branch: 'main', credentialsId: 'JNK'
      }
    }
    stage('Build & Test') {
      steps {
        sh 'cd backend && mvn clean package -DskipTests'
      }
    }
    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('SonarQube') {
          sh 'cd backend && mvn sonar:sonar -Dsonar.projectKey=backend -Dsonar.login=$SONAR_TOKEN'
        }
      }
    }
    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }
}
